stages:
  - test
  - build image

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  SBT_OPTS: "-sbt-launch-dir .sbt/launchers -sbt-dir .sbt -ivy .ivy2 -Dsbt.color=true -Dscala.color=true"
  ARTIFACTORY_USERNAME: cicd-innovation
  ARTIFACTORY_URL: https://artifactory-horw.int.toradex.com/artifactory
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "device_registry"
  MYSQL_USER: "device_registry"
  MYSQL_PASSWORD: "device_registry"

image: artifactory-horw.int.toradex.com/ota-docker-dev-horw/tdx-inno-ci-scala:0.0.1

services:
  - name: docker:dind

default:
  cache:
    when: always
    key: device-registry
    paths:
      - .ivy2/
      - .sbt/

test:
  stage: test
  services:
    - name: mariadb:10.4
      alias: db
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --max_connections=1000
  variables:
    DB_URL: "jdbc:mariadb://db:3306/device_registry"
  before_script:
    - echo "CREATE DATABASE device_registry_test; CREATE DATABASE device_registry_ptest; GRANT ALL PRIVILEGES ON \`device\_registry%\`.* TO 'device_registry'@'%'; FLUSH PRIVILEGES; " > db_user.sql
    - until mysqladmin ping --protocol=TCP -h db -P 3306 -u root -proot; do echo waiting for mysql; sleep 1; done
    - mysql -v -h db -u root -proot < db_user.sql
  script:
    - sbt test

include:
  - project: rd/innovation/continuous-delivery/ci-container-build
    file: gitlab-ci-templates/jfrog-sbt-docker-publish.yaml

build docker image:
  stage: build image
  only:
    - master
  extends: .jfrog-sbt-docker-publish
  variables:
    ARTIFACTORY_REPO: ota-docker-dev-horw
    SERVICE_NAME: device-registry
