stages:
  - test
  - build image
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "director_v2"
  MYSQL_USER: "director_v2"
  MYSQL_PASSWORD: "director_v2"
  SBT_OPTS: "-sbt-launch-dir .sbt/launchers -sbt-dir .sbt -ivy .ivy2 -Dsbt.color=true -Dscala.color=true"
  ARTIFACTORY_USERNAME: cicd-innovation
  ARTIFACTORY_URL: https://artifactory-horw.int.toradex.com/artifactory
  SERVICE: director

default:
  cache:
    key: director
    when: always
    paths:
      - .ivy2/
      - .sbt/
  image: artifactory-horw.int.toradex.com/ota-docker-dev-horw/tdx-inno-ci-scala:0.0.1
  services:
    - name: mariadb:10.4
      alias: db
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --max_connections=1000
    - name: docker:dind

test:
  stage: test
  variables:
    DB_URL: "jdbc:mariadb://db:3306/$MYSQL_DATABASE"
  before_script:
    - echo "GRANT ALL PRIVILEGES ON \`director%\`.* TO 'director_v2'@'%'; FLUSH PRIVILEGES; " > db_user.sql
    - until mysqladmin ping --protocol=TCP -h db -P 3306 -u root -proot; do echo waiting for mysql; sleep 1; done
    - mysql -v -h db -u root -proot < db_user.sql
  script:
    - sbt test

include:
  - project: rd/innovation/continuous-delivery/ci-container-build
    file: gitlab-ci-templates/jfrog-sbt-docker-publish.yaml
  - project: 'rd/platform/deploy-env'
    ref: master
    file: '/gitlab/deploy-core-service.yml'

build docker image:
  stage: build image
  only:
    refs:
      - master
      - merge_requests
  extends: .jfrog-sbt-docker-publish
  variables:
    ARTIFACTORY_REPO: ota-docker-dev-horw
    SERVICE_NAME: director-v2
    BUILD_NAME: ota-docker-director
